YAPP-Github/20th-ALL-Rounder-Team-1-Web

.github/auto_assign.yml
---
---
해당 yml 파일과 auto_assign 플러그인을 활용하여 저희가 직접 할당자와 리뷰어를 작성하지 않고도 자동 등록 할 수 있습니다. PR을 작성하는 시점에서는 노출되지 않지만 실제 PR이 작성 완료되었을 때 플러그인에 의해 자동 추가 됩니다.
approve 이후에 머지시켜서 실제로 잘 동작하는지 테스트 PR을 올려서 확인해보도록 하겠습니다.
---
---
https://github.com/apps/auto-assign  // 깃허브에서 어떻게 사용하면 되는지 자세히 설명해주고 있습니다.
=> ✨ 리뷰어 자동 지정 파일 추가

.github/auto_assign.yml
---
---
수정 전으로 하면 Reviewers, Assignees 둘다 수동님으로 설정되는 것 같네요 ㅋㅋ
---
---
=> :bug: assigner 변경

inquirer.js, package.json, yarn.lock
---
> <img width="607" alt="스크린샷 2022-05-05 오전 1 11 49" src="https://user-images.githubusercontent.com/57230590/166725205-eaa8d670-42df-4d48-bb1b-a14dfaeb9ba8.png">
> <br/> script 명령어가 많아지고 앞으로도 더 추가될 예정이기 때문에 효율적으로 명령어를 실행하기 위한 설정을 추가합니다. 항상 `yarn start` 명령어만을 사용하면 되고 그 이후에 원하는 script 명령어를 선택해서 사용하면 됩니다.
---
---
---
=> ✨ inquirer 추가

.github/workflows/main.yml
---
---
추가 PR에서 상세하게 작성하도록 하겠습니다.
---
---
=> ✨ CI/CD를 위한 github actions 구성

.dockerignore, .github/workflows/main.yml, Dockerfile
---
---
요 PR도 추후에 한번에 정리하도록 하겠습니다!
---
---
=> ✨ 도커 설정 추가와 포트 번호 수정

.gitignore, README.md, src/api/index.ts, src/components/index.ts, src/hooks/index.ts, src/pages/index.ts, src/types/index.ts, src/utils/index.ts
---
---
그때 공유드렸던 것처럼 `export default`를 사용하지 않으며, 각 폴더의 `index.ts`에서 모든 파일을 `export * from '파일이름'` 합니다.
---
---
=> ✨ 폴더 구조 확립

package-lock.json
---
---
실수로 이거 날려서 도커 빌드에서 에러가 납니다!! ㅠㅠ
---
---
=> :bug: package-lock 파일 재작성

.babelrc.js, package.json, yarn.lock
---
---
해당 플러그인을 추가하지 않으면 타입스크립트 요소를 인식하지 못합니다!!!
---
---
=> :sparkles: @babel/preset-typescript 요소 추가

src/components/common/Button.tsx
=> [Weekand-1005] [공통 컴포넌트] 버튼 컴포넌트 만들기

src/App.tsx, src/components/common/PageLayout.tsx
---
입력된 title에 따라 맞는 PageLayout을 생성할 수 있습니다.
정확한 디자인이 나오면 그에 맞게 수정할 예정입니다.
---
---
---
=> [Weekand-1009] PageLayout 만들기

src/style/GlobalStyle.ts, src/style/reset.ts
---
---
---
---
https://codingmoondoll.tistory.com/entry/%ED%94%84%EB%A1%A0%ED%8A%B8%EC%97%94%EB%93%9C-%EC%84%B1%EB%8A%A5-%EC%B5%9C%EC%A0%81%ED%99%94-5-%EC%9B%B9-%ED%8F%B0%ED%8A%B8-%EC%B5%9C%EC%A0%81%ED%99%94
=> [Weekand-1013] 폰트 설정

src/App.tsx, src/components/common/Input.tsx, src/components/index.ts, src/utils/index.ts, src/utils/validation.ts
---
- 특정 Input에 대한 검증의 조건은 다음과 같습니다.
1. 이메일 (email)
- 글자수 최대 320자
- 이메일 형식 체크
- 필수값
2. 인증번호 (authNumber)
- 인증 번호 6자리가 맞는지
- 글자수 최대 6자
- 필수값
3. 닉네임 (nickName)
- 글자수 최대 12자
- 중복된 닉네임인지
- 등록 가능한 닉네임인지
- 필수값
4. 비밀번호 (password)
- 글자수 최대 50자
- 최소 8자
- 숫자, 영어, 특수문자 최소 1개씩 포함
- 필수값
5. 비밀번호 재입력 (retypedPassword)
- 입력한 비밀번호와 일치하는 지
- 필수값
6. 일정 명 (planTitle)
- 글자수 최대 10자
- 필수값
7. 시간 (time)
- 필수값
8. 기간 (date)
- 필수값
9. 카테고리 명 (categoryTitle)
- 글자수 최대 15자
- 필수값
- Validation을 확인하는 함수는 utils/validation.ts로 분리하였습니다.
> App.tsx에 추가되어 있는 Input 테스트용 …
=> [Weekand-1006] [공통 컴포넌트] 인풋 컴포넌트 만들기

src/App.tsx, src/components/common/DebounceInput.tsx, src/components/index.ts
---
나중에 검색 api가 구축되면 빠르게 적용할 수 있도록 주석을 추가해놨습니다.
---
- Debounce의 필요성과 사용 방법에 대해 학습 및 적용해 볼 수 있었습니다:)
---
- Debounce 시간에 대해 일단은 0.4s를 기준으로 설정했습니다! 
Debounce 시간 제한에 대해 정해진 규칙이나 의견을 제안해주시면 감사하겠습니다:)
---
- https://velog.io/@skawnkk/debounce-throttle
=> [Weekand-1019] 디바운싱 인풋 사용을 위한 커스텀 훅 작성

src/style/styled.d.ts, src/style/theme.ts
---
폰트와 관련하여 추가될 내용들이 있는데 아직 디자인쪽에서 확정이 나지 않았습니다.
---
---
---
=> [Weekand-1024] 새롭게 추가된 색상 반영

src/style/styled.d.ts, src/style/theme.ts
=> [Weekand-1026] styled component 타입 수정

package.json, src/index.tsx, yarn.lock
---
GraphQL Apollo 초기 세팅 관련 요소를 추가했습니다.
나중에 서버 구축 완료 후, 해당 주소를 추가하면 됩니다.
---
---
---
=> [Weekand-1023] graphQL 기본 세팅

src/style/styled.d.ts, src/style/theme.ts
=> [Weekand-1027] 폰트 스타일 추가 및 폰트 색상을 인자로 받을 수 있는 형태로 변경

src/components/common/Interest.tsx
---
조건에 맞게 선택 가능한 관심사를 최대 3개로 제한했습니다.
---
---
---
=> [Weekand-1037] 관심사 최대 3개만 선택되도록 수정

src/pages/Login.tsx, src/style/styled.d.ts, src/style/theme.ts
=> [Weekand-1038] 폰트명 수정

package.json, src/components/calender/Calender.tsx, src/components/calender/CalenderBody.tsx, src/components/calender/CalenderHeader.tsx, src/components/calender/index.ts, src/hooks/index.ts, src/hooks/useDate.tsx, yarn.lock
---
---
https://user-images.githubusercontent.com/57230590/172408051-07085a0e-e511-4fe0-86cf-1f81c29d3453.mov
dayjs는 꽤나 많은 기능이 있다...!!
---
---
=> [Weekand-1017] 모달에 들어갈 캘린더 만들기

src/App.tsx, src/components/common/Input.tsx, src/pages/FindPassword.tsx, src/pages/Login.tsx, src/pages/index.ts
=> [Weekand-1029] 비밀번호 찾기 페이지

src/pages/Login.tsx
=> [Weekand-1051] 로그인 페이지 UI 개발 완성

.eslintrc.js, package.json, src/App.tsx, src/components/calender/Calender.tsx, src/components/calender/CalenderBody.tsx, src/components/layout/ModalLayout.tsx, src/contexts/SettingContext.tsx, src/hooks/useDate.tsx, src/index.tsx, src/pages/Login.tsx, src/style/theme.ts, yarn.lock
=> [Weekand-1052] import 구문 정리를 위한 플러그인 추가

package.json, yarn.lock
---
---
---
---
- https://github.com/zloirock/core-js/issues/500
=> [Weekand-1058] ES6 관련 코드 작성 안되던 오류 수정

public/index.html, src/App.tsx, src/common/Button.tsx, src/pages/agreement/index.tsx, src/pages/index.ts
---
https://user-images.githubusercontent.com/57230590/174801935-856aa9ab-4723-4583-bba6-c4c97d2d9828.mov
---
---
---
=> [Weekand-1041] 이용 약관 동의 페이지

src/App.tsx, src/common/layout/PageLayout.tsx, src/hooks/index.ts, src/hooks/useBackgroundColor.tsx, src/utils/background.ts, src/utils/index.ts
---
---
https://stackoverflow.com/questions/58442168/why-useeffect-doesnt-run-on-window-location-pathname-changes
`location.pathname`의 변화를 리액트에서 읽지 못하고 있었습니다. 확인해보니 react-router를 사용해야 했습니다 ㅎㅎ..
---
---
=> [Weekand-1072] 배경 색이 정상적으로 변경되지 않는 이슈

src/hooks/useBackgroundColor.tsx
=> [Weekand-1075] background color 목록 추가

public/index.html
=> [Weekand-1076] og: image url 변경

src/pages/register/components/ValidationControlledInput.tsx, src/pages/register/components/ValidationUncontrolledInput.tsx, src/pages/register/index.tsx, src/types/index.ts
---
기존에는 그냥 버튼을 클릭할 수 있게 두었는데 지난 회의에서 이야기한 버튼들의 disabled 처리를 하였습니다.
---
---
---
=> [Weekand-1078] 회원가입 페이지 input validation 고도화

src/App.tsx, src/common/Interest.tsx, src/common/layout/PageLayout.tsx, src/hooks/useBackgroundColor.tsx, src/pages/login/index.tsx, src/pages/register/components/ValidationUncontrolledInput.tsx, src/pages/register/index.tsx
=> [Weekand-1080] 회원가입 플로우 자잘한 수정 반영

src/App.tsx, src/common/FloatingButton.tsx, src/common/index.ts, src/style/GlobalStyle.ts
=> [Weekand-1042] 플로팅 버튼 작성

src/common/Header.tsx
---
블라인드 텍스트들을 넣으면서 조금 개선해볼 수 있는 부분들을 개선해보았습니다. 단순 css와 관련된 것들 때문에 코드가 너무 길어지는 것 같아서 이것들을 classnames 라이브러리를 활용하여 좀 더 깔끔하게 개선해보았습니다.
+) 추후에 알람 버튼과 리스트는 따로 컴포넌트로 분리해도 좋을 것 같아 보이네요.
---
---
---
=> [Weekand-1081] 헤더 코드 개선

src/common/calender/Calender.tsx, src/common/calender/CalenderBody.tsx, src/common/calender/CalenderHeader.tsx, src/pages/home/index.tsx
=> [Weekand-1084] 캘린더 완성 및 메인 페이지 적용

src/common/FloatingButton.tsx
=> [Weekand-1085] 플로팅 버튼의 위치가 고정되도록 수정

src/common/Interest.tsx, src/pages/home/index.tsx, src/pages/setting/components/Accessibility.tsx, src/pages/setting/components/EditProfile.tsx, src/pages/setting/components/Question.tsx, src/pages/setting/components/SettingMenu.tsx, src/pages/setting/components/SettingSidebar.tsx, src/pages/setting/index.tsx, src/utils/setting.tsx
---
- 컴포넌트 연결 및 변경된 디자인 요소를 수정했습니다.
---
---
---
=> [Weekand-1083] 세팅페이지: 접근성 설정 컴포넌트 연결

src/pages/home/components/FriendStories.tsx, src/pages/home/components/FriendStory.tsx, src/utils/dummyData.ts
---
- 이름 중앙 정렬 및, 특정 크기를 초과했을 때 ...으로 표시됩니다.
---
---
---
=> [Weekand-1090] 메인 페이지 친구 스토리 목록 수정

.eslintrc.js, package.json, src/api/index.ts, src/api/register.tsx, src/common/input/Input.tsx, src/common/input/ValidationUncontrolledInput.tsx, src/index.tsx, src/pages/register/index.tsx, src/pages/setting/components/EditProfile.tsx, src/utils/validation.ts, webpack.common.js, yarn.lock
---
.env 파일을 만들어서 
`REACT_APP_SERVER_URL={서버 url}` 을 추가해주시면 됩니다!
---
a9b08d4998ed86abded203d91ceb0b26b121f654 해당 부분을 참고해서 쿼리 구문을 작성해주시면 될 것 같습니다!
---
---
=> [Weekand-1089] 회원가입 api 연결

webpack.common.js
---
---
---
---
https://velog.io/@kyoung-jnn/Webpack-Webpack%EC%9C%BC%EB%A1%9C-%ED%99%98%EA%B2%BD-%EB%B3%80%EC%88%98-%EC%82%AC%EC%9A%A9%ED%95%98%EA%B8%B0
=> [Weekand-1092] netlify에서 환경변수에 접근할 수 있도록 설정 추가

src/App.tsx, src/api/agreement.tsx, src/api/index.ts, src/common/input/Input.tsx, src/contexts/RegisterContext.tsx, src/contexts/index.ts, src/index.tsx, src/pages/agreement/index.tsx, src/pages/register/index.tsx, src/pages/selectInterest/index.tsx
---
---
suspense를 바깥 쪽에만 감싸니까 관심사 선택페이지가 리다이렉트 되면서 뒤에 ?#이 url에 붙으면서 컨텍스트의 데이터가 날라가는 문제가 있었습니다. 일단 해당 페이지만 개별의 서스펜스로 감싸서 문제를 해결했는데 이와 관련해서 학습이 필요할 것 같습니다.
---
---
=> [Weekand-1088] 관심사 선택 api 연결

src/common/Toast.tsx, src/contexts/ToastContext.tsx
=> [Weekand-1095] 토스트 관련 코드 개선

src/api/agreement.ts, src/api/index.ts, src/api/login.ts, src/api/register.ts, src/pages/login/index.tsx, src/utils/index.ts, src/utils/storage.ts
=> [Weekand-1087] 로그인 api 연결

src/common/Interest.tsx, src/pages/selectInterest/index.tsx
=> [Weekand-1096] 관심사 3개 이상 선택시 토스트 메시지 노출

src/pages/getTempPassword/index.tsx, src/utils/validation.ts
=> [Weekand-1097] 임시 비밀번호 발급 페이지 토스트 구체화

src/common/calender/Calender.tsx, src/common/calender/CalenderBody.tsx, src/common/calender/CalenderHeader.tsx
=> [Weekand-1103] 데이터를 외부에서 받아오는 형태로 수정

src/common/CategorySubMenu.tsx, src/common/popup/CreateCategoryPopup.tsx, src/common/popup/PopUp.tsx, src/contexts/PopUpContext.tsx
---
https://user-images.githubusercontent.com/72953316/183065266-895ad1d9-ff10-44dc-a7a9-669642d429ec.mov
---
---
---
=> [Weekand-1104] 카테고리 생성 데이터 연결
